config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'home#index'
  get 'home/index'
  get 'home/computerforcause'
  get 'home/vision'
  get 'home/objectives'
  get 'home/about'
  get 'home/contact'
  get 'contact-me', to: 'messages#new', as: 'new_message'
  post 'contact-me', to: 'messages#create', as: 'create_message'
  get 'donations', to: 'donations#donations'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities


    can :read, :all                   # allow everyone to read everything
    if user && (user.has_role? :admin)
      can :access, :rails_admin       # only allow admin users to access Rails Admin
      can :dashboard, :rails_admin                  # allow access to dashboard
      if user.has_role? :superadmin
        can :manage, :all             # allow superadmins to do anything
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :user

  after_create :send_email_to_donar

  private
    def send_email_to_donar
      DonationMailer.with(user: self.user, donation: self).thanks_email.deliver_later
    end
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :body
  validates :name, :email, :body, presence: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  after_create :assign_default_role
  has_many :donations

  def assign_default_role
    self.add_role(:newuser) if self.roles.blank?
  end

  #used for displaying in the rails admin list boxes
  def title
    if (self.first_name && self.first_name.length != 0)
      self.first_name + ' ' + self.last_name
    else
      self.email
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_path, :alert => exception.message
  end

  protected
  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password])
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :date_of_birth, :address, :contact_number, :gender, :email, :password, :current_password])
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController

  def donations
    if current_user
      sum = 0
      @donations = current_user.donations
      @donations.each { |a| sum+=a.amount }
      @total = sum
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @message = 'HELLO'
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)

    if @message.valid?
      MessageMailer.contact_me(@message).deliver_now
      redirect_to root_url, notice: "Thanks for contacting us, we have received your message and we shall get back to you shortly."
    else
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:name, :email, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def display_user_name
    if (current_user.first_name && current_user.first_name.length != 0)
      current_user.first_name + ' ' + current_user.last_name
    else
      current_user.email
    end
  end
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/email_helper.rb
module EmailHelper
  def email_image_tag(image, **options)
    attachments[image] = File.read(Rails.root.join("public/#{image}"))
    image_tag attachments[image].url, **options
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/application/_footer.html.erb
<style>
/* Sticky footer styles
-------------------------------------------------- */
html {
  position: relative;
  min-height: 100%;
}
body {
  /* Margin bottom by footer height */
  margin-bottom: 0px;
}
.footer {
  position: absolute;
  bottom: 0;
  width: 100%;
  /* Set the fixed height of the footer here */
  height: 60px;
  background-color: grey;
}


/* Custom page CSS
-------------------------------------------------- */
/* Not required for template or sticky footer method. */

.container {
  width: auto;
  max-width: 680px;
  padding: 0 15px;
}
.container-fluid .text-muted {
  margin: 20px 0;
  color: white;
}
</style>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-100393454-1', 'auto');
  ga('send', 'pageview');

</script>
<!-- Part 1: Wrap all page content here -->
<footer class="footer">
  <div class="container-fluid">
    <div class="pull-right text-muted">
      <%= social_share_button_tag("Dhisha") %>
    </div>
    <p class="text-muted pull-left">Copyright &copy; 2017 &middot; <b>Dhisha Human Development Trust.</b></p>
  </div>
</footer>

app/views/application/_header.html.erb
<nav class="navbar navbar-default" style="margin-bottom: 0px;>
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"></a>
      </div>


      <div class="collapse navbar-collapse" id="navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">

        <li><a href="/home/index"><i class="fa fa-home" aria-hidden="true"></i> Home</a></li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-thumbs-o-up" aria-hidden="true"></i> Support a cause <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/home/computerforcause"><i class="fa fa-desktop" aria-hidden="true"></i> Computers for a cause</a></li>
            <li role="separator" class="divider"></li>
            <li><a><%= render 'paypal_donate_text' %></a></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-info-circle" aria-hidden="true"></i> Know more <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/home/vision"><i class="fa fa-eye" aria-hidden="true"></i> Vision</a></li>
            <li><a href="/home/objectives"><i class="fa fa-hashtag" aria-hidden="true"></i> Objectives</a></li>
            <li><a href="/home/about"><i class="fa fa-university" aria-hidden="true"></i> About us</a></li>
            <li><a href="/home/contact"><i class="fa fa-users" aria-hidden="true"></i> Contacts</a></li>
          </ul>
        </li>

        <li><a href="/contact-me"><i class="fa fa-question-circle" aria-hidden="true"></i> Reach us</a></li>

        <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><b> Hi, <%= display_user_name %> <span class="caret"></span></b></a>
              <ul class="dropdown-menu">
                <li><a href="/donations"><i class="fa fa-money" aria-hidden="true"></i> My donations</a></li>
                <li><a href="/users/edit"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Update profile</a></li>
                <li><a href="/contact-me"><i class="fa fa-question-circle" aria-hidden="true"></i> Submit query</a></li>
                <% if (current_user.has_role? :admin) || (current_user.has_role? :superadmin) %>
                  <li role="separator" class="divider"></li>
                  <li><a href="/admin"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> Administration</a></li>
                  <li><a href="/admin/donation/new"><i class="fa fa-usd" aria-hidden="true"></i> Create Donation</a></li>
                <% end %>
                <li><a href="/users/sign_out" data-method="delete"><i class="fa fa-power-off rediconcolor" aria-hidden="true"></i> Log out</a></li>
              </ul>
            </li>
          <% else %>
              <li><%= link_to " Login", "#login", "data-toggle" => "modal", "data-target" => "#login", style: "color: orange;" %></li>
              <li><%= link_to " Sign up", "#sign_up", "data-toggle" => "modal","data-target" => "#sign_up", style: "color: orange;" %></li>
        <% end %>
      </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

app/views/application/_paypal_donate_button.html.erb
<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_blank">
  <input type="hidden" name="cmd" value="_s-xclick">
  <input type="hidden" name="hosted_button_id" value="EFT6JCT3T2HRW">
  <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
  <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>

app/views/application/_paypal_donate_text.html.erb
<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_blank">
  <input type="hidden" name="cmd" value="_s-xclick">
  <input type="hidden" name="hosted_button_id" value="EFT6JCT3T2HRW">
  <button type="submit" class="btn btn-default">
    <i class="fa fa-cc-paypal"></i> Donate via PayPal
  </button>
  <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>

app/views/donations/donations.html.erb
<% if @donations.exists? %>

<button class="btn btn-lg btn-success" type="button">
  Total donation made till date is  <span class="badge"><%= @total %></span>
</button>

<table class="table table-bordered">
  <tr>
    <th>S No</th>
    <th>Cause</th>
    <th>Amount</th>
    <th>Currency</th>
    <th>Comment</th>
    <th>Date (yyyy-mm-dd) </th>
  </tr>
  <% @donations.each_with_index do |donation, index| %>
    <tr>
      <td><%= index+1 %></td>
      <td><%= donation.cause %></td>
      <td><%= donation.amount %></td>
      <td><%= donation.currency %></td>
      <td><%= donation.comment %></td>
      <td><%= donation.created_at.strftime("%F") %></td>
    </tr>
  <% end %>
  </table>
  <div class="text-center"><%= render 'paypal_donate_text' %></div>

<% else %>
  <div class="text-center"><h1>Sorry, no donations found.<%= render 'paypal_donate_text' %></h1></div>
<% end %>

app/views/home/_carousel.html.erb
<!-- Carousel
================================================== -->
<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="4000">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag "hands_carousel.png", alt: "First slide", class: "first-slide" %>
      <div class="container">
        <div class="carousel-caption">
          <h1 class="font-color-black"><b>Dhisha aims at eradicating poverty by providing skill development training.</b></h1>
          <%= render 'sign_up_btn_page' %>
        </div>
      </div>
    </div>
    <div class="item">
      <%= image_tag "children_carousel.png", alt: "Second slide", class: "second-slide" %>
      <div class="container">
        <div class="carousel-caption">
          <h1 class="font-color-black"><b>Dhisha human development trust is a humanitarian non-profit organization.</b></h1>
          <%= render 'sign_up_btn_page' %>
        </div>
      </div>
    </div>
    <div class="item">
      <%= image_tag "quotes_carousel.png", alt: "Third slide", class: "third-slide" %>
      <div class="container">
        <div class="carousel-caption">
          <h1 class="font-color-white"><b>Dhisha promotes education and health.</b></h1>
          <%= render 'sign_up_btn_page' %>
        </div>
      </div>
    </div>
  </div>
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div><!-- /.carousel -->

app/views/home/_sign_up_btn_page.html.erb
<% if !user_signed_in? %>
  <%= link_to "Sign up today", "#sign_up", "data-toggle" => "modal", :class => 'btn btn-lg btn-primary animated slideInLeft', "data-target" => "#sign_up" %>
  <%= link_to "Already a member? Sign in.", "#login", "data-toggle" => "modal", :class => 'btn btn-lg btn-danger animated slideInRight', "data-target" => "#login" %>
<% end %>

app/views/home/about.html.erb
<div class="jumbotron backgroundSnow notofontclass_size">
  <h2><strong>About Dhisha</strong></h2>
  <p>
    Dhisha human development trust is a humanitarian development voluntary American and Indian based non-profit organization registered under 501(c)(3) under internal revenue code and also registered under Indian Charitable Trust Act 1950 established for the integrated development and upliftment of the poor and marginalized, orphans, minorities, urban poor, informal labour sector, downtrodden and under privileged in the society irrespective of case, creed and religion, and other backward classes inspired from and committed towards achieving the MILLENNIUM DEVELOPMENT GOALS set by the UNITED NATIONS ORGANISATION.
  </p>
  <p>
  It is secular, apolitical and non-profit organization that came into existence with a mission to all round development of society.
  </p>
</div>

app/views/home/computerforcause.html.erb
<div class="container-fluid backgroundSnow notofontclass_size">
<!-- Portfolio Item Heading -->
<!-- Portfolio Item Row -->
<div class="row">
  <h1><strong>&nbsp;Computers With Causes</strong></h1>

  <div class="col-md-3">
    <i class="fa fa-laptop bigIconSize15 darksalmoniconcolor wow rollIn" aria-hidden="true"></i>
  </div>

  <div class="col-md-9">
    <h3><strong>Who we help...!</strong></h3>
    <p>The best way to learn about giving through Computers with Causes is through your own personal experience.
    The Computers with Causes program Run by the Dhisha, a 501(c)3 Non-Profit Charitable Organization collects used working Laptop PC’s, Desktops, Mobile Workstations, Projectors, Laptop accessories for its initiative to make classroom’s digital, suitable for building computer labs in Govt Schools that cant afford such technology and help make an amazing difference to the students, teachers and families we support.</p>
    <p>There is a great need to extend and repurpose our technology. We help students, teachers, Households seeking vocational retraining and educating and other great causes. It’s an unforgettable experience that works to enhance and align the spirit of everyone in our communities. Whatever you create with your giving, goodwill, financial relief, education, progress, hope... we will all leave with a
    renewed outlook and motivation for doing the same.</p>
    <p>We are a place to learn about giving, and a place to discover how to make a meaningful difference in the lives of others. For the most impactful giving we offer transparency like no other. The opportunity to see, hear and fully understand the difference you have made in the lives of others.</p>
  </div>

</div>

<div class="row">

  <h3><strong>&nbsp;A few more examples of what we do with your computer donations and surplus new electronics include</strong></h3>
  <div class="col-md-12">
    <ul>
      <li>Govt/ Aided High Schools, Colleges.</li>
      <li>Local Libraries.</li>
      <li>Support for students, teachers, and parents.</li>
      <li>School Reform and Experimental Education.</li>
      <li>Welfare Organizations.</li>
    </ul>
  </div>
</div>

<div class="row">
<h2><strong>&nbsp;IRS Rules for Donating Computer Equipment</strong></h2>
<p>
  <ul>
    <li>Dhisha takes the guesswork out of the whole Computer Donation process by offering easy to understand and useful information.</li>
    <li>For individuals, the charitable deduction for contributions of technology equals the fair market value (retail used value in the current market place) of the donated property. The donation is tax deductible for the year in which our organization receives the equipment. Shipping costs are also tax deductible under applicable rules and regulations.</li>
    <li>You are eligible for a tax break if you donate computer of electronic gadget to a library, school, or a nonprofit program such as Dhisha. Business donors can deduct the un-depreciated value of the computer, and individuals can deduct the current market value of a computer. </li>
    <li>Example: A computer and related software with a purchase price of $3,000, valued at $1000 at time of contribution, receives a $1000 deduction on Schedule A. A written receipt must be received. The receipt that we provide will have your name on it, the name and identifying number of computers with causes, and the model and type of equipment donated.</li>
  </ul>
</p>
</div>
<div class="row">
  <p>
    If you may wish to support this cause, please submit your request
    <a href="/contact-me" class="btn btn-lg btn-primary wow lightSpeedIn"> by clicking here...!</a>
  </p>
</div>
  <p>
    <div class="row">
    </div>
  </p>
</div>

app/views/home/contact.html.erb
<div class="jumbotron backgroundSnow notofontclass_size">
  <h2><strong>Our Address</strong></h2>

  <p>
    Dhisha, USA
  </p>
  <p>
    2710 Titania Pl,
  </p>
  <p>
    Simi Valley, CA, 93063
  </p>
  <p>
    Ph: 601-832-3341
  </p>
  <p>
    If you have any questions or want to reach us, please submit your query
    <a href="/contact-me" class="btn btn-lg btn-primary"> by clicking here...<i class="fa fa-question-circle" aria-hidden="true"></i></a>
  </p>
</div>

app/views/home/index.html.erb
<%= render 'carousel' %>

<!-- Marketing messaging and featurettes
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container marketing">


  <!-- Three columns of text below the carousel -->
    <div class="row-full backgroundPaypal">
      <div class="text-center animated jackInTheBox">
        <i class="fa fa-cc-paypal honeydewiconcolor fa-5x" aria-hidden="true"></i> <%= render 'paypal_donate_button' %>
      </div>
    </div>

    <div class="row-full backgroundGold">
    <div class="row font-color-indigo">
      <div class="col-lg-4">
        <i class="fa fa-book bigIconSize12 blueiconcolor wow rollIn" aria-hidden="true"></i>

        <section class="wow slideInUp">
          <h2>Education </h2>
          <p>The root cause for most of the social problems is poverty, which is due to lack of education and skill set required for obtaining suitable employment.</p>
          <!-- <p><a class="btn btn-default" href="/home/vision" role="button">Know more &raquo;</a></p> -->
        </section>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <i class="fa fa-child bigIconSize12 greeniconcolor wow pulse" aria-hidden="true"></i>

        <section class="wow slideInDown">
          <h2>Empowerment</h2>
          <p>Our mission is to contribute to the social and financial development of the neglected sector of our city. We are and will continue to work against all odds to assist these people in the best possible manner.</p>
          <p><a class="btn btn-danger" href="/home/objectives" role="button">Know more &raquo;</a></p>
        </section>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <i class="fa fa-heartbeat bigIconSize12 rediconcolor wow bounceInRight" aria-hidden="true"></i>

        <section class="wow slideInRight">
          <h2>Health</h2>
          <p> Dhisha aims at reducing the financial burden of health care on poor households and enhance their access to quality health care.</p>
          <!-- <p><a class="btn btn-default" href="/home/vision" role="button">Know more &raquo;</a></p> -->
        </section>
      </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->
  </div>


  <div class="row-full backgroundBottom">
    <div class="row font-color-chartreuse">
      <div class="col-lg-4 wow rubberBand">
        <i class="fa fa-eye bigIconSize12 darksalmoniconcolor wow rollIn" aria-hidden="true"></i>
        <h2>Our Vision</h2>
        <p>The root cause for most of the social problems is poverty, which is due to lack of education and skill set required
          for obtaining suitable employment. Dhisha aims at eradicating poverty by providing skill development training (using skill India initiative
          by Govt of India effectively) to unemployed and bringing economically weaker section to mainstream by the power of quality education, skill training
          and awareness.</p>
        <!-- <p><a class="btn btn-default" href="/home/vision" role="button">Know more &raquo;</a></p> -->
      </div>
      <div class="col-lg-4 wow rotateIn">
        <i class="fa fa-calendar-check-o bigIconSize12 cornsilkiconcolor wow rollIn" aria-hidden="true"></i>
        <h2>Our Mission</h2>
        <p>Our mission is to contribute to the social and financial development of the neglected sector of our city. We are and will continue to work against all odds to assist these people in the best possible manner.</p>
        <p><a class="btn btn-danger" href="/home/vision" role="button">Know more &raquo;</a></p>
     </div>
      <div class="col-lg-4 wow lightSpeedIn">
        <i class="fa fa-handshake-o bigIconSize12 lightskyblueiconcolor wow rollIn" aria-hidden="true"></i>
        <h2>And lastly, more of what we want to do</h2>
        <p>Equity in access to health care services and the related financial burden on households, hence, has been one of the major concerns of Indian health system. The challenges are related to reducing the financial burden of health care on poor households and enhance their access to quality health care.</p>
        <!-- <p><a class="btn btn-default" href="/home/vision" role="button">Know more &raquo;</a></p> -->
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dhisha</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application" %>
    <link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script type="text/javascript">
       $(function () {
          $("#myModal").modal({show:false});
      });
    </script>
     <script>
      new WOW({mobile: false}).init();
     </script>
    </head>

  <body>

    <%= render "welcome/login_modal" %>
    <%= render "welcome/sign_up_modal" %>
    <%= render 'header' %>

    <%= bootstrap_flash :class => 'no-bottom-margin' %>

    <%= yield %>
    <%= render 'footer' %>
  </body>
</html>

app/views/messages/new.html.erb
<div class="row">
  <div class="col-md-offset-3 col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4>Please submit your request below</h4>
      </div>
      <div class="panel-body">
      <%= form_for @message, url: create_message_url do |f| %>
        <%= notice %>
        <%= @message.errors.full_messages.join(', ') %>

        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control', placeholder: 'Please enter your name' %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control', placeholder: 'Please enter your email id' %>
        </div>
        <div class="form-group">
          <%= f.label :content %>
          <%= f.text_area :body, rows: 10, class: 'form-control', placeholder: 'Briefly describe your query here' %>
        </div>
        <%= f.submit 'Submit Request', class: 'btn btn-primary' %>
        <a class="btn btn-danger pull-right" href="/">Go Back</a>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/welcome/_login_modal.html.erb
<div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="loginModal">
  <div class="modal-dialog" role="document">
  <div class="modal-content">
      <div class="modal-header">
        <button class="close" data-dismiss="modal">x</button>
        <h2>Sign in</h2>
      </div>
      <div class="modal-body">
      <div class="form-group">
      <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
        <div><%= f.label :email %><br />
        <%= f.email_field :email, :autofocus => true, placeholder: 'Please enter your email id.', :class => 'form-control' %></div>

        <div><%= f.label :password %><br />
        <%= f.password_field :password, placeholder: 'Please enter your password.', :class => 'form-control' %></div>

        <% if devise_mapping.rememberable? -%>
          <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
        <% end -%>
        <div><%= f.submit "Sign in", :class => 'btn btn-small btn-success' %></div>
        <% end %>
      </div>
      </div>
      <div class="modal-footer">
      <%= render "devise/shared/links" %>
      </div>
    </div>
  </div>
</div>

app/views/welcome/_sign_up_modal.html.erb
<div class="modal fade" id="sign_up" tabindex="-1" role="dialog" aria-labelledby="signUpModal">
  <div class="modal-dialog" role="document">
  <div class="modal-content">
      <div class="modal-header">
        <button class="close" data-dismiss="modal">x</button>
        <h2>Sign Up</h2>
      </div>

        <div class="modal-body">
        <div class="form-group">
          <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
          <%= devise_error_messages! %>

          <div><%= f.label :email %><br />
          <%= f.email_field :email, :autofocus => true, placeholder: 'Please enter your email id.', :class => 'form-control' %></div>

          <div><%= f.label :password %><br />
          <%= f.password_field :password, placeholder: 'Please enter your password.', :class => 'form-control' %></div>

          <div><%= f.label :password_confirmation %><br />
          <%= f.password_field :password_confirmation, placeholder: 'Reconfirm your password.', :class => 'form-control' %></div>
        </div>
        </div>
        <div class="modal-footer">
          <p><div><%= f.submit "Sign up", :class => 'btn btn-small btn-success' %></div></p>
          <p><a href="#" class="btn btn-small" data-dismiss="modal">Close</a></p>
        </div>
      <% end %>
    </div>
  </div>
</div>